grate-driver/xf86-video-opentegra

src/Makefile.am, src/exa.c, src/exa.h, src/tegra_stream.c, src/tegra_stream.h
I have got a couple of kernel crashes which were caused by a commands pushbuf
overflow. We are not checking whether there is some space left in the pushbuf
before adding a new command to it, the tegra_stream addresses this shortcoming
and also makes code a bit cleaner. It is definitely a kernel bug as well, there
shouldn't be a crash on a command stream dump.
[  179.285724] ---- syncpts ----
[  179.285738] id 0 (00-(null)) min 13383 max 13446
[  179.285753] id 3 (03-54200000.dc) min 10799 max 0
[  179.285802] ---- channels ----
[  179.285811] 0: fifo:
[  179.285821] FIFOSTAT 80100c40
[  179.285827] [empty]
[  179.285839] 0-54140000.gr2d:
[  179.285853] active class 51, offset 0000, val 20000000
[  179.285865] DMAPUT 00000168, DMAGET 00000168, DMACTL 00000000
[  179.285876] CBREAD …
=> exa: use tegra_stream for commands submission

src/exa.c, src/tegra_stream.c
The maximum number of a HOST1X gather fetches is 16384, a higher value
would result in an integer overflow on CDMA submission. If we'd need to
submit a higher number of words, an additional pushbufs should be used for
the job.
=> exa: reduce commands buffer size

src/exa.c, src/tegra_stream.c
The gather maximum words count is 16383, not 16384.
=> exa: reduce commands buffer size by one

src/exa.c, src/xv.c
The shadow buffer is quite useless and the Xv bug is unlikely to be triggered, but let's fix them.
=> Couple corrections

src/driver.c, src/drmmode_display.c
MATE Desktop Environment causes a Xorg crash, probably some new DRM mode property type is used now (or been added) casing a NULL dereference in Opentegra. Another minor change is the drmOpen usage which would avoid wrong device opening in case of modular Tegra DRM kernel driver as there could be other DRM device module loaded earlier.
=> MATE crash fix

src/drmmode_display.c
We had a bug reported with a touchscreen where we could end up
in here with a NULL cursor, so let's not crash the X server.
Signed-off-by: Dave Airlie <airlied@redhat.com>
Reviewed-and-Tested-by: Daniel Martin <consume.noise@gmail.com>
Signed-off-by: Peter Hutterer <peter.hutterer@who-t.net>
=> modesetting: handle NULL cursor in drmmode_set_cursor.

src/tegra_stream.c
Commit 01f46bc (exa/tegra_stream: correctly prepare pushbuf) erroneously added
couple of unrelated lines of code that broke compilation, remove them.
Thanks to @dipolukarov for pointing to the bug.
=> tegra_stream: compilation fix

src/exa.c, src/tegra_stream.c, src/tegra_stream.h
Arto Merilainen of NVIDIA confirmed that we should increment syncpoint
after each HW trigger because it might be not safe to adjust registers
while operation hasn't completed yet, let's do it.
=> exa/tegra_stream: increment syncpoint after each HW operation trigger

src/dri2.c
libdrm-tegra doesn't forbid caching after getting FLINK name of BO anymore, caching should be forbidden explicitly now.
=> dri2: Forbid caching of the exported BO

src/driver.c
This should fix building with older Xorg versions.
../../src/driver.c: In function ‘TegraProbeHardware’:
../../src/driver.c:241:38: error: ‘struct xf86_platform_device’ has no member named ‘flags’
if (platform_dev && (platform_dev->flags & XF86_PDEV_SERVER_FD)) {
^
../../src/driver.c:241:48: error: ‘XF86_PDEV_SERVER_FD’ undeclared (first use in this function)
if (platform_dev && (platform_dev->flags & XF86_PDEV_SERVER_FD)) {
^
../../src/driver.c:241:48: note: each undeclared identifier is reported only once for each function it appears in
../../src/driver.c:242:9: error: implicit declaration of function ‘xf86_get_platform_device_int_attrib’ [-Werror=implicit-function-declaration]
fd = xf86_get_platform_device_int_attrib(platform_dev, ODEV_ATTRIB_FD, -1);
^
../../src/driver.c:242:9: …
=> driver: check whether XF86_PDEV_SERVER_FD is defined

src/driver.c
We actually want to check that it is defined and not != 0. That also makes this check consistent with other checks for XSERVER_PLATFORM_BUS in the code.
=> driver: s/if/ifdef/ for XSERVER_PLATFORM_BUS

src/driver.c
Rootless Xorg would pass DRM FD to opentegra, but still we should invoke drm_tegra_close() to release libdrm stuff.
=> driver: close drm in a case of passed FD

configure.ac, src/Makefile.am, src/TLSF/COPYING, src/TLSF/Changelog, src/TLSF/GPL.txt, src/TLSF/LGPL-2.1.txt, src/TLSF/Makefile.am, src/TLSF/README, src/TLSF/target.h, src/TLSF/tlsf.c, src/TLSF/tlsf.h, src/driver.h, src/exa.c, src/exa.h
There is some memory wasted by small pixmaps because BO's size is rounded
up to the size of page by CMA. To resolve this, use a pool memory allocator
that aggregates small allocation into the pools.
Since this patch refactors pixmap allocation quite a lot, I've incorporated
other minor feature to this patch. Now a known non-acceleratable pixmap,
like 1-bit BPP, is strictly fallback-allocation.
=> exa: implement memory pool allocator

src/exa.c
I'm not exactly sure when ModifyPixmapHeader could be invoked, so better
to just clear the pointer.
=> exa: unset fence pointer on pixmap data release

src/driver.c
Opentegra should be able to properly detect HW cursor presence in runtime. Let's enable it by default now, HW cursor is supported by upstream kernel since v4.17.
=> driver: enable HW cursor by default with newer Xorg versions

src/xv.c
=> xv: fix src plane coordinates

src/Makefile.am, src/driver.h, src/exa.c, src/exa_mm.c, src/exa_mm_fridge.c, src/memcpy_vfp.c, src/memcpy_vfp.h, src/pool_alloc.c
Add accelerated  memcpy that uses VFP instructions to copy 128 bytes at once, it gives significant boost to copying from uncached buffer. Inspired by results of https://github.com/ssvb/tinymembench.
> ==========================================================================
== Framebuffer read tests.                                              ==
==                                                                      ==
== Many ARM devices use a part of the system memory as the framebuffer, ==
== typically mapped as uncached but with write-combining enabled.       ==
== Writes to such framebuffers are quite fast, but reads are much       ==
== slower and very sensitive to the alignment and the selection of      ==
== CPU instructions which are used for accessing memory. …
=> Accelerated  memcpy

src/driver.c, src/drm_plane.c, src/xv.c, src/xv.h
Add new alternative non-blocking API which doesn't block Xorg on updating plane's state. Later we may transit to async atomic updates, once DRM core will expose async commits to userspace and Tegra DRM will support it too (grate-kernel has it https://github.com/grate-driver/linux/commit/bb12b422f376614ada8abf8d5a122a0b2b5acaeb, I'll send it out to upstream soon'ish).
I'm going to merge this PR couple days later, after some more testing and if there won't be any objections. WIP VDPAU patch is [here](https://github.com/digetx/libvdpau-tegra/commit/6e82b2ec7c4175dc4b12bf790c88687d585c22c6).
=> Xv non-blocking VDPAU API

src/dri2.c, src/driver.c, src/exa.c, src/vblank.c, src/xv.c
In commit 4c602ea I completely forgot about legit cases where EXA intialization may fail. This PR contains  fix and two minor clean-up patches.
=> Ignore screen initialization errors

src/xv.c
16bit framebuffer format that didn't work for Xv, works now.
=> Xv 16bit framebuffer support

src/driver.c, src/exa.c, src/xv.c
- the DRM atomic API is disabled now for Xorg in [Linux kernel](    https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=26b1d3b527e7bf3e24b814d617866ac5199ce68d
), but Opentegra needs it for Xv
- libvdpau-tegra now will be able to perform better when display is rotated
=> Minor update

src/exa.c
malloc_trim is not available in musl-libc
Signed-off-by: David Heidelberg <david@ixit.cz>
=> exa: make driver compilable outside glibc

src/tegradrm/opentegra_lib.h
- musl-libc doesn't include it by default
Signed-off-by: David Heidelberg <david@ixit.cz>
Fixes: https://github.com/grate-driver/xf86-video-opentegra/issues/61
=> opentegra_lib: include time.h
